[theme]
primaryColor="#FF6F00"       # Oranye sebagai warna utama
backgroundColor="#fff0e6"    # Oranye sangat pucat untuk background
secondaryBackgroundColor="#ffffff"  # Putih untuk widget
textColor="#000000"          # Hitam untuk teks
font="sans serif"